carro/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
#from .views import guardar_toquen

app_name="carro"

urlpatterns = [
        path("agregar/<str:producto_id>/", views.agregar_producto, name="agregar"),
        path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
        path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
        path("limpiar/", views.limpiar_carro, name="limpíar"),
]

login/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, HttpResponse




urlpatterns = [
    path('',views.inicio, name="inicio"),
    path('login', views.loginPage, name="login"),
    path('registro', views.registro, name='registro'),
    path('logout', views.logoutUser, name='logout'),
]

misitio/urls.py
from django.contrib import admin
from django.urls import path, include
from sitio import views

app_name= 'sitio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sitio.urls')),
    path('carro/', include('carro.urls')),
    path('', include('login.urls')),
]

sitio/urls.py
from django.urls import path
from sitio import views
from django.conf import settings
from django.conf.urls.static import static
#from .views import guardar_toquen

urlpatterns = [
        path('', views.sitio, name= "sitio"),
        path('login',views.login, name="login"),
        path('registro',views.registro, name="registro"),
        path('carrito',views.carrito, name="carrito"),

]

carro/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'lastname', 'username', 'password', 'email', 'address', 'city', 'commune']

carro/views.py
from django.shortcuts import render, redirect
from sitio import views
from .carro import Carro
from django.http import HttpResponse, HttpResponseBadRequest
import requests


# Create your views here.

def agregar_producto(request, producto_id):
   # url = 'http://3.86.154.125:8000'
   # response = requests.get.items('http://3.86.154.125:8000/productos').json()
   # return render(request, {
   #     'response': response,
   #     'url': url

   # })
   # for obj in response:

   #     if obj.cod_prod == producto_id:
    #        producto = array[{obj.cod_prod, obj.descripcion, obj.pr_venta, obj.imagen}]

    carro=Carro(request)
    #producto= Productos.objects.get(id=producto_id)
    carro.agregar(producto=producto_id)
    return redirect("sitio")

def eliminar_producto(request, producto_id):

    carro=Carro(request)
    producto= Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("misitio")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id-producto_id)
    carro.restar_producto(producto=producto)
    return redirect("misitio")

def limpiar_carro(request, producto_id):

    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("misitio")

login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm

# Create your views here.
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('inicio')
        else:
            messages.info(request,'Usuario o clave incorrecta')

    context = {}
    return render(request,"login/login.html",context)
def logoutUser(request):
    logout(request)
    return redirect('inicio')

def registro(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request,'Cuenta creada para '+ user)
            return redirect('login')
    context = {'form':form}
    return render(request,"login/registro.html", context)

def inicio(request):
    return render (request,"sitiowebapp/index.html")

sitio/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest
import requests

# Create your views here.

def sitio(request):
    url = 'http://54.174.155.180:8000'
    response = requests.get('http://54.174.155.180:8000/productos').json()

    return render(request, "sitio/index.html", {
        'response': response,
        'url': url
    })


def login(request):
        return render(request,"login/login.html")

def registro(request):
        return render(request,"sitio/registro.html")

def carrito(request):
        return render(request, "sitio/carrito.html")

login/templates/login/login.html
{% extends "sitio/base.html" %}
{% load static %}
{% block boostrap %}

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

{% endblock %}

{% block css %}
    <link href="{% static 'login/css/style_login.css' %}" rel="stylesheet" >
{% endblock %}
<!--{% block login%}activo{% endblock %}-->

{% block content %}
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn login_btn" type="submit" value="Login">
                           </div>
                </form>


            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}
            {{form.errors}}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    ¿No tienes una cuenta? <a href="{% url 'registro' %}" class="ml-2">Sign Up</a>
                </div>
        
            </div>
        </div>
    </div>
</div>



{% endblock %}

login/templates/login/registro.html
{% extends "sitiowebapp/base.html" %}
{% load static %}
{% block boostrap %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
{% endblock %}
{% block css %}
    <link href="{% static 'login/css/style_registro.css' %}" rel="stylesheet" >
{% endblock %}

{% block login %}activo{% endblock %}
    {% block content %}
    
           
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
                <div class="user_card">
                        <div class="d-flex justify-content-center">
                                <h3 id="form-title">Registro de Usuario</h3>
                        </div>
                        <div class="d-flex justify-content-center form_container">

                                <form method="POST" action="">
                                        {% csrf_token %}
                                        <div class="input-group mb-3">
                                                <div class="input-group-append">
                                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                                </div>
                                                {{form.username}}
                                        </div>
                                        <div class="input-group mb-2">
                                                <div class="input-group-append">
                                                        <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                                                </div>
                                                {{form.email}}
                                        </div>
                                        <div class="input-group mb-2">
                                                <div class="input-group-append">
                                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                                </div>
                                                {{form.password1}}
                                        </div>
                                        <div class="input-group mb-2">
                                                <div class="input-group-append">
                                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                                </div>
                                                {{form.password2}}
                                        </div>

                                           <div class="d-flex justify-content-center mt-3 login_container">
                                                 <input class="btn login_btn" type="submit" value="Registrar">
                                           </div>
                                </form>
                        </div>
                        <div class="error">
                                {{form.errors}}
                        </div>
                        <div class="mt-4">
                                <div class="d-flex justify-content-center links">
                                        ¿Ya tienes una cuenta? <a href="{% url 'login' %}" class="ml-2">Login</a>
                                </div>
                        </div>
                </div>
        </div>
</div>
    
     
    
    {% endblock %}
    {% block js %}<script src="{% static 'login/js/registro/registro.js' %}"></script> {% endblock %}

sitio/templates/carro/widget.html
<table class="table table-bordered" style="color: black;">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro de compras

            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.descripcion}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn brn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn brn-sm btn-success">-</a>
                        {{value.precio}} CLP
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin Articulos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}} CLP
            </td>
        </tr>
    </tfoot>
</table>

sitio/templates/sitio/base.html
<html>
<head>
    {% load pwa %}
    {% progressive_web_app_meta %}
    {% load static %}
    <title>Mau Fuenbus</title>
    <meta name="viewport" content="width=device-width, user-scalable=no,
    initial-scale=1, maximum-scale=1, minimum-scale=1">
    
    
    {% block boostrap %} {% endblock %}
    {% block boostrap4 %} {% endblock %}
     {% block css %} {% endblock %}
    <link rel="stylesheet" href="{% static 'sitio/font/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'sitio/css/style_base.css' %}">
   
<!-- The core Firebase JS SDK is always required and must be listed first -->
    <!--<script src="https://www.gstatic.com/firebasejs/8.1.2/firebase-app.js"></script> -->
    <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase-app.js"></script>
    
    <script src="https://www.gstatic.com/firebasejs/3.9.0/firebase-messaging.js"></script>
    
    <!-- TODO: Add SDKs for Firebase products that you want to use
         https://firebase.google.com/docs/web/setup#available-libraries -->
    
    <script>
      // Your web app's Firebase configuration
      var firebaseConfig = {
        apiKey: "AIzaSyD4fcrcvxhWanaghzlJKrDZNLpU0O5kcmc",
        authDomain: "fotografia-55188.firebaseapp.com",
        projectId: "fotografia-55188",
        storageBucket: "fotografia-55188.appspot.com",
        messagingSenderId: "391930439203",
        appId: "1:391930439203:web:7b91aad3cd5db494757396"
      };
      // Initialize Firebase
      firebase.initializeApp(firebaseConfig);
    
      let messaging = firebase.messaging();
    
      //enlace service worker
      navigator.serviceWorker
      .register('./serviceworker.js')
      .then(function(register){
    
          messaging.useServiceWorker(register);
    
          //solicitud de permiso a los usuarios
    
          messaging.requestPermission()        
          .then(function(){
    
              console.log("El usuario ha aceptado notificaciones")     
              
              return messaging.getToken();
          })
          .then(function(token){
              console.log(token);
    
              //envio de token a django para guardar en bd
                fetch('guardar-token/',{
                    method:'post',
                    headers:{
                        'Content-Type':'application/json',
                        'Accept':'application/json'
                    },
                    body:JSON.stringify({
                        'token':token
                    })
                })
                .then(function(resultado){
                    console.log("se ha guardado el token")
                })
                .catch(function(e){
                    console.log("el usuario no ha aceptado")
                })
    
          })
    
          .catch(function(e){
              console.log("El usuario no ha aceptado las notificaciones")
          })
      })
    
      //recepcion de notificaciones push
      messaging.onMessage(function(payload){
          console.log("ha llegado notificacion")
          let data = payload;
          console.log(data);
    
        let title = payload.notification.title;
        let options = {
            body: payload.notification.body,
            icon: payload.notification.icon
        }
        let mensaje = new Notification(title, options);
    
      });
    
    </script>
</head>
<body>
{% block content %}




    {% endblock %}
    
    <script src="{% static 'login/js/index/menu.js' %}"></script>
    
    {% block bsjs %} {% endblock %}
</body>

</html>

sitio/templates/sitio/indexRESPALDO.html
<html lang="es">

<head>
    {% load static %}
    <title>PcFucktory</title>
    <meta charset="UTF=8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="{% static 'sitio/css/base.css'%}">
    <link rel="stylesheet" href="{% static 'sitio/css/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

</head>

<body>
    <header class="top">
        <!--Logo-->
        <div class="header-logo">
            <img src="{% static 'sitio/img/logo.png'%}" alt="PcFucktory">
        </div>
        <!--Buscador-->
        <div class="header-top-buscador">
            <form action="#" method="post">
                <input type="search" name="Search" placeholder="Buscar articulo..." required="">
                <button type="submit" class="btn btn-default" aria-label="Left Align">
                        <i class="bucar" aria-hidden="true"><i class="fas fa-search"></i></i>
                    </button>
            </form>
        </div>
        <!--header menu usuario-->
        <div class="header-usuario">
            <nav class="icon-usuario"><i class="fas fa-user"></i> Mi Cuenta</a>
                <ul class="userMenu-submenu">
                    <li><a href="login">Iniciar Sesion</a></li>
                    <li><a href="#">Ver Perfil</a></li>
                    <li><a href="#">Contacto</a></li>
                    <li><a href="#">Cerrar Sesion</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <header class="bot">
        <!--menu articulos-->
        <div class="header-bot"><i class="fas fa-bars"> Productos</i>
            <nav class="menu-desplegable">
                <div class="lista">
                    <div class="sub-lista">
                        <div class="seccion">Partes de PC
                            <ul class="desplegable">
                                <li><a href="#">Procesadores</a></li>
                                <li><a href="#">Placas madre</a></li>
                                <li><a href="#">Ram</a></li>
                                <li><a href="#">Discos duros</a></li>
                                <li><a href="#">Gpu</a></li>
                                <li><a href="#">Fuentes de poder</a></li>
                                <li><a href="#">Refrigeracion</a></li>
                                <li><a href="#">Cables</a></li>
                                <li><a href="#">Gabinetes</a></li>
                            </ul>
                        </div>
                        <div class="seccion">Pantallas
                            <ul class="desplegable">
                                <li><a href="#">Monitores</a></li>
                                <li><a href="#">Lcd</a> </li>
                                <li><a href="#">Led</a> </li>
                                <li><a href="#">Smart-Tv</a></li>
                                <li><a href="#">Proyectores</a> </li>
                            </ul>
                        </div>
                        <div class="seccion">Notebooks
                            <ul class="desplegable">
                                <li><a href="#">Hp</a></li>
                                <li><a href="#">Asus</a></li>
                                <li><a href="#">Lenovo</a></li>
                                <li><a href="#">Mac</a></li>
                                <li><a href="#">Huawei</a></li>
                                <li><a href="#">Dell</a></li>
                                <li><a href="#">Acer</a></li>
                            </ul>
                        </div>
                        <div class="seccion">Moviles
                            <ul class="desplegable">
                                <li><a href="#">Celulares</a></li>
                                <li><a href="#">Tablet</a></li>
                                <li><a href="#">Kindle</a></li>
                            </ul>
                        </div>
                        <div class="seccion">Accessories
                            <ul class="desplegable">
                                <li><a href="#">PowerBank</a></li>
                                <li><a href="#">Cargadores celular</a></li>
                                <li><a href="#">Cargadores notebooks</a></li>
                                <li><a href="#">Soporte para celulares</a></li>
                                <li><a href="#">Soporte para tablet</a></li>
                                <li><a href="#">Smartwach</a></li>
                                <li><a href="#">Carcasas</a></li>
                            </ul>
                        </div>
                        <div class="seccion">Otros
                            <ul class="desplegable">
                                <li><a href="#">Pasta disipadora</a></li>
                                <li><a href="#">Pilas</a></li>
                                <li><a href="#">Luces rgb para mas fps</a></li>
                                <li><a href="#">Sillas</a></li>
                                <li><a href="#">Webcam</a></li>
                                <li><a href="#">Microfonos</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>

        </div>
        <!--Carrito de compra-->
       <!-- <div class="carro" href=""><i class="fas fa-shopping-cart"></i> Carrito</div> -->
    </header>
    <div class="container">

        <div style="float: right;">

            <p class="fas fa-shopping-cart">Carrito</p><br>
            <p class="fas fa-shopping-cart"></p><br>
            {% include "carro/widget.html" %}
        </div>
        <div class="row">
            {% for obj in response %}
                <div class="col-md-3 col-sm-12 col-lg-4">
                    <div class="card text-center" style="width: 80%; margin: 10px 10px">
                   <!-- {{ obj.id }} - {{ obj.descripcion }} -->
                    <img src= "{{url}}{{obj.imagen }}"  class="card-img-top " alt="{{ obj.descripcion }}"/>
                    <div class="card-body text-center"A>
                        <h5 class="card-tittle">{{obj.descripcion}}</h5>
                        <p class="card-text">{{obj.cod_prod}} CLP</p>
                    </div>
                        <div class='card-footer text-center'>
                            <a href="{% url 'carro:agregar' obj.cod_prod %}" class="btn btn-success">Añadir al carrito</a>
                        </div>
                    </div>
                    </div>
            {% endfor %}

        </div>
    </div>

    <!--Footer ordenado, falta posicionar abajo de la pagina-->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>Medios de pago</h4>
                    <ul>
                        <li><a href="#"><i class="fab fa-cc-mastercard"> Mastercard</i></a></li>
                        <li><a href="#"><i class="fab fa-cc-paypal"> Paypal</i></a></li>
                        <li><a href="#"><i class="fab fa-cc-visa"> Visa</i></a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Menú</h4>
                    <ul>
                        <li><a href="#">Mi cuenta</a></li>
                        <li><a href="#">Contactar un vendedor</a></li>
                        <li><a href="#">Página principal</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Novedades</h4>
                    <ul>
                        <li><a href="#">SmartWatch</a></li>
                        <li><a href="#">Mochilas</a></li>
                        <li><a href="#">Notebooks</a></li>
                        <li><a href="#">Cámaras</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Social Links</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="derechos">
            <h4>&copy; 2021 Pcfucktory. Todos los derechos reservados.</h4>
        </div>
    </footer>



</body>

</html>

sitio/templates/sitio/login.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" type="text/css" href="{% static 'sitio/css/login.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="card">
            <h4 class="card-header">Login</h4>
            <div class="card-body">
                <div class="alert alert-danger" role="alert">
                    Usuario y/o Contraseña incorrecta.
                </div>
                <form data-toggle="validator" role="form" method="post" action="#">
                    <input type="hidden" class="hide" id="csrf_token" name="csrf_token" value="C8nPqbqTxzcML7Hw0jLRu41ry5b9a10a0e2bc2">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Email / Usuario</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-envelope-open-o" aria-hidden="true"></i></span>
                                    </div>
                                    <input type="text" class="form-control" name="login_email" value="" pattern=".{4,}" title="Cuatro(4) o mas caracteres" required="">
                                </div>
                                <div class="help-block with-errors text-danger"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Contraseña</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-unlock" aria-hidden="true"></i></span>
                                    </div>
                                    <input type="password" name="login_password" class="form-control" pattern=".{4,}" title="Cuatro(4) o mas caracteres" required="">
                                </div>
                                <div class="help-block with-errors text-danger"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="checkbox checkbox-primary">
                            <input id="checkbox_remember" type="checkbox" name="remember">
                            <label for="checkbox_remember"> Recordar</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <input type="hidden" name="redirect" value="">
                            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Login" name="submit">
                        </div>
                    </div>
                </form>
                <div class="clear"></div>
                <i class="fa fa-user fa-fw"></i> ¿No tienes cuenta aún? <a href="registro">Regístrate</a><br>
                <i class="fa fa-undo fa-fw"></i> ¿Se te olvidó tu contraseña? <a href="#">Recupérala</a>
            </div>
        </div>
    </div>
</div>